name: cosmetics_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  lottie: ^3.3.2
  animate_do: ^4.2.0
  pin_code_fields: ^8.0.1
  circular_countdown_timer: ^0.2.4
  google_maps_flutter: ^2.14.0
  maps_launcher: ^3.0.0+1
  geolocator: ^14.0.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  assets :
    - assets/images/
    - assets/icons/
    - assets/lotties/


  uses-material-design: true

fonts:
  - family: Montserrat
    fonts:
      - assets: assets/fonts/montserrat.ttf


